language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.4
  - rbx-3

gemfile:
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_2.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DB=postgresql
  - DB=mysql
  - DB=sqlite3

sudo: false

before_install:
  - rvm get master

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS sexy_scopes_spec;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE sexy_scopes_spec;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS sexy_scopes_spec;'; fi"

script: bundle exec rake

matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
  exclude:
    # ActiveRecord 5 requires Ruby 2.2.0
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5_1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5_2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5_1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5_2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_edge.gemfile


branches:
  only:
    - master
